spring:
  data.rest.base-path: /api
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        use_sql_comments: true
        default_batch_fetch_size: 500
    database: postgresql

logging.level:
  org.hibernate.SQL: debug
